-- Feature Engineering Queries

-- 1. Base Application Features
DROP TABLE IF EXISTS feat_application;
CREATE TABLE feat_application AS
SELECT 
    SK_ID_CURR,
    TARGET,
    AMT_INCOME_TOTAL AS APP_INCOME_TOTAL,
    AMT_CREDIT AS APP_CREDIT_AMOUNT,
    AMT_ANNUITY AS APP_ANNUITY,
    DAYS_BIRTH AS APP_DAYS_BIRTH,
    DAYS_EMPLOYED AS APP_DAYS_EMPLOYED,
    EXT_SOURCE_1 AS APP_EXT_SOURCE_1,
    EXT_SOURCE_2 AS APP_EXT_SOURCE_2,
    EXT_SOURCE_3 AS APP_EXT_SOURCE_3,
    (AMT_CREDIT / NULLIF(AMT_INCOME_TOTAL, 0)) AS APP_CREDIT_INCOME_RATIO,
    (AMT_ANNUITY / NULLIF(AMT_INCOME_TOTAL, 0)) AS APP_ANNUITY_INCOME_RATIO
FROM application_train;

-- 2. Traditional Credit Features (Bureau)
DROP TABLE IF EXISTS feat_bureau;
CREATE TABLE feat_bureau AS
SELECT 
    SK_ID_CURR,
    COUNT(SK_ID_BUREAU) AS BUREAU_CREDIT_COUNT,
    SUM(CASE WHEN CREDIT_ACTIVE = 'Active' THEN 1 ELSE 0 END) AS BUREAU_ACTIVE_COUNT,
    SUM(AMT_CREDIT_SUM) AS BUREAU_TOTAL_CREDIT,
    SUM(AMT_CREDIT_SUM_DEBT) AS BUREAU_TOTAL_DEBT,
    SUM(AMT_CREDIT_SUM_DEBT) / NULLIF(SUM(AMT_CREDIT_SUM), 0) AS BUREAU_DEBT_RATIO,
    AVG(DAYS_CREDIT) AS BUREAU_AVG_DAYS_CREDIT
FROM bureau
GROUP BY SK_ID_CURR;

-- 3. Alternative Behavioural Features (Previous Applications)
DROP TABLE IF EXISTS feat_prev_app;
CREATE TABLE feat_prev_app AS
SELECT 
    SK_ID_CURR,
    COUNT(SK_ID_PREV) AS PREV_APP_COUNT,
    SUM(CASE WHEN NAME_CONTRACT_STATUS = 'Approved' THEN 1 ELSE 0 END) AS PREV_APPROVED_COUNT,
    SUM(CASE WHEN NAME_CONTRACT_STATUS = 'Refused' THEN 1 ELSE 0 END) AS PREV_REFUSED_COUNT
FROM previous_application
GROUP BY SK_ID_CURR;

-- 4. Alternative Behavioural Features (Installments)
DROP TABLE IF EXISTS feat_installments;
CREATE TABLE feat_installments AS
SELECT 
    SK_ID_CURR,
    COUNT(*) AS INST_TOTAL_COUNT,
    SUM(CASE WHEN DAYS_ENTRY_PAYMENT IS NOT NULL AND DAYS_INSTALMENT IS NOT NULL
             AND DAYS_ENTRY_PAYMENT > DAYS_INSTALMENT THEN 1 ELSE 0 END) AS INST_LATE_PAYMENT_COUNT,
    CAST(SUM(CASE WHEN DAYS_ENTRY_PAYMENT IS NOT NULL AND DAYS_INSTALMENT IS NOT NULL
                  AND DAYS_ENTRY_PAYMENT > DAYS_INSTALMENT THEN 1 ELSE 0 END) AS REAL)
        / NULLIF(COUNT(CASE WHEN DAYS_ENTRY_PAYMENT IS NOT NULL AND DAYS_INSTALMENT IS NOT NULL THEN 1 END), 0)
        AS INST_LATE_PAYMENT_RATIO,
    SUM(CASE WHEN AMT_PAYMENT IS NOT NULL AND AMT_INSTALMENT IS NOT NULL
             AND AMT_PAYMENT < AMT_INSTALMENT THEN 1 ELSE 0 END) AS INST_UNDERPAYMENT_COUNT,
    SUM(CASE WHEN DAYS_ENTRY_PAYMENT IS NULL OR AMT_PAYMENT IS NULL THEN 1 ELSE 0 END)
        AS INST_PAYMENT_MISSING_COUNT
FROM installments_payments
GROUP BY SK_ID_CURR;

-- 5. Master Feature Table
DROP TABLE IF EXISTS feature_master;
CREATE TABLE feature_master AS
SELECT 
    a.*,
    COALESCE(b.BUREAU_CREDIT_COUNT, 0) AS BUREAU_CREDIT_COUNT,
    COALESCE(b.BUREAU_ACTIVE_COUNT, 0) AS BUREAU_ACTIVE_COUNT,
    COALESCE(b.BUREAU_TOTAL_CREDIT, 0) AS BUREAU_TOTAL_CREDIT,
    COALESCE(b.BUREAU_TOTAL_DEBT, 0) AS BUREAU_TOTAL_DEBT,
    CASE WHEN b.SK_ID_CURR IS NULL THEN 0 ELSE b.BUREAU_DEBT_RATIO END AS BUREAU_DEBT_RATIO,
    COALESCE(b.BUREAU_AVG_DAYS_CREDIT, 0) AS BUREAU_AVG_DAYS_CREDIT,
    COALESCE(p.PREV_APP_COUNT, 0) AS PREV_APP_COUNT,
    COALESCE(p.PREV_APPROVED_COUNT, 0) AS PREV_APPROVED_COUNT,
    COALESCE(p.PREV_REFUSED_COUNT, 0) AS PREV_REFUSED_COUNT,
    COALESCE(i.INST_TOTAL_COUNT, 0) AS INST_TOTAL_COUNT,
    COALESCE(i.INST_LATE_PAYMENT_COUNT, 0) AS INST_LATE_PAYMENT_COUNT,
    CASE WHEN i.SK_ID_CURR IS NULL THEN 0 ELSE i.INST_LATE_PAYMENT_RATIO END AS INST_LATE_PAYMENT_RATIO,
    COALESCE(i.INST_UNDERPAYMENT_COUNT, 0) AS INST_UNDERPAYMENT_COUNT,
    COALESCE(i.INST_PAYMENT_MISSING_COUNT, 0) AS INST_PAYMENT_MISSING_COUNT
FROM feat_application a
LEFT JOIN feat_bureau b ON a.SK_ID_CURR = b.SK_ID_CURR
LEFT JOIN feat_prev_app p ON a.SK_ID_CURR = p.SK_ID_CURR
LEFT JOIN feat_installments i ON a.SK_ID_CURR = i.SK_ID_CURR;
